# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Compile for Windows

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


permissions:
  contents: read

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install nuitka pyqt6 requests GitPython
    - name: Compile
      continue-on-error: true
      run: |
        cd client
        echo Y | python -m nuitka launcher.py --standalone --enable-plugin=pyqt6 --disable-console
    - name: Tar files
      run: copy launcher.ui client/launcher.dist && cd client && zip -r launcher.zip launcher.dist
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: launcher.zip
        path: client/launcher.zip
